version: '3'
services:
  nginx:
    restart: always
    image: nginx:1.17.4-alpine
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx:/etc/nginx/conf.d
  web:
    build:
        context: . 
        dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    