FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
# CMD ["gunicorn", "--chdir", "lamia_django", "--bind", ":8000", "lamia_django.wsgi:application"]