# Generated by Django 3.0.3 on 2020-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200507_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoobject',
            options={'verbose_name': 'Задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='todoobject',
            name='owner',
        ),
        migrations.AddField(
            model_name='todoobject',
            name='job_type',
            field=models.CharField(choices=[('blank', 'blank'), ('backend', 'backend'), ('frontend', 'frontend')], default='blank', max_length=30, verbose_name='Тип Раюоты'),
        ),
        migrations.AlterField(
            model_name='todoobject',
            name='status',
            field=models.CharField(choices=[('inprocces', 'В процессе'), ('done', 'Выполнена')], default='inprocces', max_length=30, verbose_name='Статус задачи'),
        ),
    ]
