# Generated by Django 3.0.3 on 2020-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200512_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoobject',
            name='main_text',
            field=models.CharField(default='', max_length=50, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoobject',
            name='job_type',
            field=models.CharField(choices=[('blank', 'blank'), ('backend', 'backend'), ('frontend', 'frontend')], default='blank', max_length=30, verbose_name='Тип Работы'),
        ),
    ]
